### ISSUE TITLE
Server throwing an error on connect

### ISSUE THREAD

**Issue by Thorinair** [gagagu/VR-Streamer-Windows-Server#2]
Hey, I don't know if here on GitHub is where I should submit error reports, but I am having some issues with the server software.

I started the server up, and iOS client up. added the process to the software, set everything up and hit "Connect to Server" on my iPhone. The screen on iPhone went gray, and the following error is displayed on desktop:
![image](https://cloud.githubusercontent.com/assets/7534126/11451994/ae870f4c-95d8-11e5-8a0d-11efe38e62a1.png)
In addition, pressing on "Refresh Process Window Position and Size" doesn't seem to do anything.

PC is  Intel Core2 Quad CPU, 8 GB of RAM, AMD Radeon R9 270x GPU, running Windows 7
iOS device is iPhone 5S, running iOS 9.1
Process I tried to add was Elite Dangerous, but no other process seems to work either.

I would love if you could help me, I tried both newer and older versions of the server and got the same error. You seem to be the only one maintaining some sort of iOS VR server and I don't have much of a choice.

**Comment by Thorinair** [comment]
Update: I have fixed the issue by enabling GDI capture. If you don't mind suggestions, maybe a suggestion to enable it should be added to the error window.

**Comment by samtulach** [comment]
HELP PLEASE!!! I have this error! How to I fix it. I have win7 64bit.

**Comment by gagagu** [comment]
There is an option you have to enable when you are using windows 7, pls activate it
