### ISSUE TITLE
Streaming Audio as well?

### ISSUE THREAD

**Issue by bfenty** [gagagu/VR-Streamer-Windows-Server#3]
I don't use Github much, so I apologize if it is inappropriate to put a feature request in as an 'issue'.

I'm curious how hard it would be to also stream the game's audio (or all PC audio, since isolating the game audio may be difficult) to the phone along with the visuals. I play Skyrim via the app, which is a great experience, with a wireless xbox controller, but for audio I still have to plug into my PC. It's easy to get a little tangled up in the wire sometimes. While I could definitely get wireless headphones to completely go wireless, I wondered if it would be possible to plug in my gaming headphones directly to my phone instead and stream the audio in the app. Is this possible? Would bandwidth become an issue?

**Comment by gagagu** [comment]
Hi, this is a good idea but to stream the audio, too it would slow down the video transfer! I guess it would be result in much more video issues. I will think about it.

**Comment by bfenty** [comment]
I thought it might-I am very impressed with how low the latency is, and how high quality! I play Skyrim with this constantly. If you do decide to implement, I'd say it should be able to be turned off if it is not needed.

Thank you for making such an awesome product!
