### ISSUE TITLE
Headtracking only with opentrack?

### ISSUE THREAD

**Issue by blackthornecl** [gagagu/VR-Streamer-Windows-Server#7]
Can i use another? becasuse everything work perfect, except head tracking , im triying to play outlast, and cant configure headtracking for this, octopus move when i move the iphone, but not in-game, any ideas?

regards!﻿

**Comment by gagagu** [comment]
Hi, I've only programmed an inferace to opentrack which is used by many games. I'm not able to implement games itself. May be outlast supports the trackir tracker? Or take a look into the mouse emulation tarcker of opentrack.
